apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gangway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gangway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gangway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gangway.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gangway
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["gangway", "-config", "/gangway/gangway.yaml"]
          env:
            - name: GANGWAY_SESSION_SECURITY_KEY
              {{- if .Values.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: sessionSecurityKey
              {{- else }}
              value: {{ .Values.config.sessionSecurityKey | quote }}
              {{- end }}
            - name: GANGWAY_CLIENT_SECRET
              {{- if .Values.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: clientSecret
              {{- else }}
              value: {{ .Values.config.clientSecret | quote }}
              {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: gangway-config
              mountPath: /gangway/
      volumes:
        - name: gangway-config
          configMap:
            name: {{ include "gangway.configMapName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
