apiVersion: v1
kind: Service
metadata:
  name: {{ include "gangway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gangway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "gangway.selectorLabels" . | nindent 4 }}
